baseURL = "https://robinopletal.com"
languageCode = "en-us"
title = "Robin Opletal"
theme = 'hugo-vitae'
enableRobotsTXT = true

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""

[params]
# Use homepage.md instead of a list of posts
homepage = false

# Add meta keywords in head part (Site Keywords or Tags of Page)
keywords = ["robinopletal","ansible","linux","security","automation","containers"]

# Add meta description in head part
description = "Robin Opletal's personal website"

# Add pagetitle to homepage <title> tag
#pagetitle = ""

# Add a subtitle to your website
subtitle = ""

# Activate to show authors on pages if available
listAuthor = true

# Add math typesetting with KaTeX (Global with this Param)
math = false

# Optional 80x80 avatar image.
# avatar = "/img/vitae.jpg"

# Optional favicons for website
favicon = true

# Add list of sections that should show up on the homepage
mainSections = ["posts"]

# Add list of Sections/Types that should no be considered by RSS
#nofeedSections = ["posts"]

# Deactivate Taxonomies for specific page types
#disableTaxoTypes = [""]

# Custom CSS applied to default styles. (Path could be "static/css/")
#customCSS = "css/custom.css"

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

# [[menu.main]]
# name = "Posts"
# url = "/posts/"
# weight = 3

[[params.social]]
name = "GitLab"
icon = "fab fa-gitlab"
url = "https://gitlab.com/opletalrobin"

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/fourstepper"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"
