baseURL: "https://robinopletal.com"
title: Robin Opletal
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Robin Opletal
  description: "Robin Opletal's space"
  keywords:
    [
      Blog,
      Website,
      Automation,
      Linux,
      Security,
      Ergonomics,
      Keyboards,
      Split,
      Terraform,
      DevOps,
      IaC,
    ]
  author: Me
  DateFormat: "2 January, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowShareButtons: true
  ShowPostNavLinks: true
  # ShowBreadCrumbs: true
  ShowToC: true
  TocOpen: true
  disableSpecial1stPost: false
  disableScrollToTop: true
  comments: false
  hidemeta: false
  hideSummary: false

  # https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#adding-custom-favicons
  # assets:
  #     # disableHLJS: true # to disable highlight.js
  #     # disableFingerprinting: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # # profile-mode
  # profileMode:
  #     enabled: false # needs to be explicitly set
  #     title: ExampleSite
  #     subtitle: "This is subtitle"
  #     imageUrl: "<img location>"
  #     imageWidth: 120
  #     imageHeight: 120
  #     imageTitle: my image
  #     buttons:
  #         - name: Posts
  #           url: posts
  #         - name: Tags
  #           url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my website :)

  socialIcons:
    - name: email
      url: "mailto:me@robinopletal.com"
    - name: matrix
      url: "https://matrix.to/#/@fourstepper:robinopletal.com"
    - name: github
      url: "https://github.com/fourstepper"
    - name: linkedin
      url: "https://www.linkedin.com/in/robin-opletal"
    - name: twitter
      url: "https://twitter.com/robinopletal"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/fourstepper/robinopletal.com/tree/main/site/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  outputs:
    home:
      - HTML
      - RSS

menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: about
      name: about
      url: /about/
      weight: 20
